### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [Danktuary/vuepress-theme-yuu#1]
1. Is it possible you can add something like this for the theme:
```
::: info 
Text here inside an information message.
:::
````

2. Is it possible you can make it so we can enable the dark theme when someone comes to the page I tried `darkTheme: true` in the settings but it doesn't seem to work.

3. Add icons (FontAwesome) perhaps to the menu so `icon: 'fas fa-home'` or something similar to that. (Example: https://nakorndev.github.io/vuepress-theme-bulma/)

4. Is it possible to use `vue-discord-messages` in this? If so, can you explain how I can do so.

**Comment by Danktuary** [comment]
Super late to reply on this but better late than never I guess. 😅 

1) I think that'd be on a VuePress level (i.e. extending frontmatter, if I'm not mistaken). Regardless, I'll take a look at it and see.

2) I'll add a `forceDarkTheme: true` page option (similar to the `forceTheme: blue` frontmatter option that already exists)

3) That'd be your own thing to add per-site; I don't wanna include the entire lib in this theme since most people may not use it.

4) It is! Install it normally (`yarn add vue-discord-messages`) and then in `/pages/.vuepress/enhanceApp.js`, add this:

```js
import VueDiscordMessage from '../../node_modules/vue-discord-message';

export default ({ Vue }) => {
	Vue.use(VueDiscordMessage);
}
```

Do note how the import is done. There's an open issue about this right now (vuejs/vuepress#451) and that's the suggested workaround. `import Package from 'package';` works in development, but when you try to build VuePress, it'll fail without this workaround.
